<?php
/**
 * Cellfire Template — Article Layout: Terms of Service
 * Assign to an article with alias "terms"
 */
defined('_JEXEC') or die;
$updated = 'March 24, 2026';
?>
<section class="cf-legal-section">
<div class="cf-container" style="max-width:860px; padding:60px 24px 100px;">

  <div class="cf-legal-header">
    <h1 class="cf-section-title">Terms of <span class="cf-gradient-text">Service</span></h1>
    <p class="cf-section-sub">Last updated: <?= $updated ?></p>
  </div>

  <div class="cf-legal-body">

    <h2>1. Acceptance of Terms</h2>
    <p>By accessing or using any Cellfire product or service — including the Cellfire mobile app,
    RF Studio, Cellfire Web Viewer, or cellfire.io (collectively, the &ldquo;Services&rdquo;) —
    you agree to be bound by these Terms of Service (&ldquo;Terms&rdquo;) and our
    <a href="/privacy">Privacy Policy</a>. If you do not agree, do not use the Services.</p>
    <p>The Services are operated by <strong>VeteranOp, LLC</strong>, an Idaho limited liability company.</p>

    <h2>2. Eligibility</h2>
    <p>You must be at least 18 years old and capable of entering a binding contract to use the Services.
    By using the Services you represent that you meet these requirements.</p>

    <h2>3. Account Registration</h2>
    <p>You must create an account to access most features. You agree to provide accurate information
    and keep your credentials confidential. You are responsible for all activity under your account.
    Notify us immediately at <a href="mailto:support@cellfire.io">support@cellfire.io</a> if you
    suspect unauthorized access.</p>
    <p>We reserve the right to suspend or terminate accounts that violate these Terms.</p>

    <h2>4. Subscriptions &amp; Billing</h2>
    <h3>Free Trial</h3>
    <p>New accounts receive a <strong>30-day free trial</strong> with full access to all features.
    No credit card is required for the trial. After 30 days your account reverts to read-only
    unless you subscribe to a paid plan.</p>

    <h3>Paid Plans</h3>
    <p>Paid subscriptions are billed monthly. All prices are in USD. Subscriptions automatically
    renew each billing period unless cancelled. You may cancel at any time through
    <a href="/account">your account page</a>; cancellation takes effect at the end of the
    current billing period — no partial refunds are issued for unused time.</p>

    <h3>Payment Processing</h3>
    <p>Payments are processed by Stripe, Inc. By subscribing you agree to
    <a href="https://stripe.com/legal" target="_blank" rel="noopener">Stripe&rsquo;s terms</a>.
    We reserve the right to change pricing with 30 days&rsquo; notice.</p>

    <h3>Refunds</h3>
    <p>Subscription fees are generally non-refundable. If you believe you were charged in error,
    contact <a href="mailto:billing@cellfire.io">billing@cellfire.io</a> within 14 days of the charge.</p>

    <h2>5. Acceptable Use</h2>
    <p>You agree <strong>not</strong> to:</p>
    <ul>
      <li>Use the Services for any unlawful purpose or in violation of any regulation</li>
      <li>Interfere with or disrupt the Services or servers connected to them</li>
      <li>Attempt to gain unauthorized access to any part of the Services</li>
      <li>Reverse engineer, decompile, or disassemble any part of the Services</li>
      <li>Use the Services to collect signal data in areas where you do not have permission to be</li>
      <li>Resell or sublicense the Services without written permission from VeteranOp, LLC</li>
      <li>Upload malicious code or interfere with other users&rsquo; use of the Services</li>
    </ul>
    <p>Signal data collected using the Cellfire app is subject to all applicable FCC regulations
    and local laws. You are solely responsible for ensuring your use of the Services complies
    with applicable law in your jurisdiction.</p>

    <h2>6. Intellectual Property</h2>
    <p>All content, software, trademarks, and data in the Services are the property of
    VeteranOp, LLC or its licensors. You may not copy, modify, distribute, or create derivative
    works without our written consent.</p>
    <p>You retain ownership of signal data you collect. By uploading data to Cellfire you grant
    VeteranOp, LLC a non-exclusive, royalty-free license to use that data in anonymized,
    aggregated form to improve the Services and the crowdsourced signal database.</p>

    <h2>7. Signal Data Accuracy</h2>
    <p>Cellfire provides cellular RF signal data as-is for informational and engineering purposes.
    <strong>We make no warranty</strong> regarding the accuracy, completeness, or fitness for any
    particular purpose of signal data, coverage maps, or propagation models generated by the Services.
    Signal data should not be used as the sole basis for critical infrastructure, life-safety, or
    regulatory compliance decisions.</p>

    <h2>8. Disclaimer of Warranties</h2>
    <p>THE SERVICES ARE PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT
    WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF
    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT
    THAT THE SERVICES WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.</p>

    <h2>9. Limitation of Liability</h2>
    <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, VETERANOP, LLC AND ITS OFFICERS, EMPLOYEES, AND
    AGENTS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE
    DAMAGES ARISING OUT OF YOUR USE OF THE SERVICES, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
    DAMAGES. OUR TOTAL LIABILITY TO YOU FOR ANY CLAIM ARISING OUT OF THESE TERMS SHALL NOT EXCEED
    THE AMOUNT YOU PAID US IN THE THREE MONTHS PRECEDING THE CLAIM.</p>

    <h2>10. Indemnification</h2>
    <p>You agree to indemnify and hold harmless VeteranOp, LLC from any claims, losses, liabilities,
    damages, and expenses (including reasonable attorneys&rsquo; fees) arising out of your use of
    the Services, violation of these Terms, or violation of any third-party rights.</p>

    <h2>11. Governing Law &amp; Disputes</h2>
    <p>These Terms are governed by the laws of the State of Idaho, without regard to conflict-of-law
    principles. Any dispute arising under these Terms shall be resolved by binding arbitration in
    Ada County, Idaho, under the rules of the American Arbitration Association, except that either
    party may seek injunctive relief in any court of competent jurisdiction.</p>

    <h2>12. Changes to Terms</h2>
    <p>We may modify these Terms at any time. We will provide at least 14 days&rsquo; notice of
    material changes by posting on this page or emailing registered users. Continued use of the
    Services after the effective date constitutes acceptance.</p>

    <h2>13. Contact</h2>
    <p><strong>VeteranOp, LLC</strong><br>
    <a href="mailto:legal@cellfire.io">legal@cellfire.io</a></p>

  </div><!-- /.cf-legal-body -->
</div>
</section>

<style>
.cf-legal-section { background: var(--cf-bg-1, #111); color: var(--cf-text-1, #eee); }
.cf-legal-header  { margin-bottom: 48px; }
.cf-legal-body h2 {
  font-size: 1.25rem; font-weight: 700; color: #fff;
  margin: 2.5rem 0 .75rem; border-bottom: 1px solid #2a2a2a; padding-bottom: .5rem;
}
.cf-legal-body h3 { font-size: 1rem; font-weight: 600; color: #ccc; margin: 1.5rem 0 .5rem; }
.cf-legal-body p, .cf-legal-body li { color: #aaa; line-height: 1.8; margin-bottom: .75rem; }
.cf-legal-body ul { padding-left: 1.5rem; margin-bottom: 1rem; }
.cf-legal-body a  { color: #4fc3f7; text-decoration: none; }
.cf-legal-body a:hover { text-decoration: underline; }
</style>
